### ISSUE TITLE
保存するcloudにVoxelGridを使うか否かをパラメータとして持たせたい

### ISSUE THREAD

**Issue by Alpaca-zip** [sbgisen/LIO-SAM#5]
**概要**
保存するpoint cloudに対して、VoxelGridを使うか否かをパラメータとして持たせたい。

**目的**
高い密度の環境地図を構築するために、保存するpoint cloudに対してVoxelGridによるダウンサンプリングをしない、という選択肢を用意したい。

**提案内容**
構築する環境地図の点群密度に関わるVoxelGridは以下。
https://github.com/sbgisen/LIO-SAM/blob/f698fddf57684edb9a793b85548b2b603119b985/src/featureExtraction.cpp#L280
https://github.com/sbgisen/LIO-SAM/blob/f698fddf57684edb9a793b85548b2b603119b985/src/mapOptmization.cpp#L1077
https://github.com/sbgisen/LIO-SAM/blob/f698fddf57684edb9a793b85548b2b603119b985/src/mapOptmization.cpp#L1082
最終的に保存するGlobal mapは`laserCloudSurfLastDS`と`laserCloudCornerLastDS`を`transformPointCloud()`して足したものであるため、これらの変数名を変えるなどして`saveMapService()`に渡すpoint cloudにVoxelGridを適用しないようにする。

**Comment by nyxrobotics** [comment]
> 最終的に保存するGlobal mapは`laserCloudSurfLastDS`と`laserCloudCornerLastDS`を`transformPointCloud()`して足したものであるため、これらの変数名を変えるなどして`saveMapService()`に渡すpoint cloudにVoxelGridを適用しないようにする。

この足し合わせる部分に当たるソースコードの場所わかりますか？

**Comment by Alpaca-zip** [comment]
> この足し合わせる部分に当たるソースコードの場所わかりますか？

以下、順を追ったものになります。
https://github.com/sbgisen/LIO-SAM/blob/f698fddf57684edb9a793b85548b2b603119b985/src/mapOptmization.cpp#L1686-L1694
https://github.com/sbgisen/LIO-SAM/blob/f698fddf57684edb9a793b85548b2b603119b985/src/mapOptmization.cpp#L466-L470
https://github.com/sbgisen/LIO-SAM/blob/f698fddf57684edb9a793b85548b2b603119b985/src/mapOptmization.cpp#L503-L509
